dependencies:
  build:
    - ruby:2.2.10

build_targets:
  - name: default
    container: 
      image: yourbase/yb_ubuntu:16.04
    commands:
        - chmod +x yourbased.sh
        - ./yourbased.sh

ci:
  builds:
    - name: default
      build_target: default
